apiVersion: apps/v1
kind: Deployment
metadata:
  name: capi-management-cluster-setup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capi-management-cluster-setup
  template:
    metadata:
      labels:
        app: capi-management-cluster-setup
    spec:
      containers:
      - name: capi-management-cluster-setup
        image: alpine:3.18
        command: ["/bin/sh", "-c"]
        args:
          - |
            # Check if the setup has already been completed
            if [ -f /etc/rancher/rke2/setup-complete ]; then
              echo "Setup already completed, skipping..."
              exit 0
            fi

            # Install necessary packages
            apk add --no-cache jq curl

            # Fetch the latest version tag
            latest_version=$(curl -s https://api.github.com/repos/kubernetes-sigs/cluster-api/releases/latest | jq -r '.tag_name')

            # Verify the version tag was fetched correctly
            if [ -z "$latest_version" ]; then
              echo "Failed to fetch the latest version of clusterctl"
              exit 1
            fi

            # Download the latest clusterctl binary
            curl -L "https://github.com/kubernetes-sigs/cluster-api/releases/download/${latest_version}/clusterctl-linux-amd64" -o /usr/local/bin/clusterctl

            # Ensure the binary is downloaded
            if [ ! -f "/usr/local/bin/clusterctl" ]; then
              echo "Failed to download clusterctl"
              exit 1
            fi

            # Make the binary executable
            chmod +x /usr/local/bin/clusterctl

            # Replace 127.0.0.1 with the actual control plane IP in the KUBECONFIG file
            CONTROL_PLANE_IP=10.230.16.37 # Or manually set the control plane IP if known
            sed -i "s/127.0.0.1/${CONTROL_PLANE_IP}/g" /etc/rancher/rke2/rke2.yaml

            # Set environment variables
            export KUBECONFIG=/etc/rancher/rke2/rke2.yaml
            export CLUSTER_TOPOLOGY=true

            # Verify the installation
            /usr/local/bin/clusterctl version

            # Initialize the management cluster
            /usr/local/bin/clusterctl init --infrastructure openstack

            # Mark the setup as complete
            touch /etc/rancher/rke2/setup-complete

            # Exit the container to prevent it from running indefinitely
            exit 0
        volumeMounts:
        - name: kubeconfig
          mountPath: /etc/rancher/rke2
      volumes:
      - name: kubeconfig
        hostPath:
          path: /etc/rancher/rke2
          type: Directory
