apiVersion: batch/v1
kind: Job
metadata:
  name: clusterctl-setup
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: clusterctl-setup
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        env:
        - name: KUBECONFIG
          value: /root/.kube/kubeconfig
        args:
          - |
            apk add --no-cache openssh-client curl
            mkdir -p /root/.ssh
            ssh -i {{ .Values.serverSetup.ssh.keyFile }} -o StrictHostKeyChecking=no {{ .Values.serverSetup.ssh.user }}@{{ .Values.serverSetup.ssh.host }} 'bash -s' < /runner/install-clusterctl.sh
            ssh -i {{ .Values.serverSetup.ssh.keyFile }} -o StrictHostKeyChecking=no {{ .Values.serverSetup.ssh.user }}@{{ .Values.serverSetup.ssh.host }} 'bash -s' < /runner/init-cluster.sh
        volumeMounts:
        - name: runner-scripts
          mountPath: /runner
      restartPolicy: OnFailure
      volumes:
      - name: runner-scripts
        configMap:
          name: runner-scripts
