apiVersion: batch/v1
kind: Job
metadata:
  name: clusterctl-setup
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: clusterctl-setup
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            apk add --no-cache openssh-client curl
            mkdir -p /root/.ssh
            cp /mnt/ssh-key/id_rsa /root/.ssh/id_rsa
            chmod 600 /root/.ssh/id_rsa
            cp ./kubeconfig/kubeconfig /tmp/kubeconfig
            ssh -o StrictHostKeyChecking=no {{ .Values.serverSetup.ssh.user }}@{{ .Values.serverSetup.ssh.host }} 'bash -s' < /runner/install-clusterctl.sh
            ssh -o StrictHostKeyChecking=no {{ .Values.serverSetup.ssh.user }}@{{ .Values.serverSetup.ssh.host }} 'bash -s' < /runner/init-cluster.sh
        volumeMounts:
        - name: ssh-key
          mountPath: /mnt/ssh-key
          readOnly: true
        - name: runner-scripts
          mountPath: /runner
      restartPolicy: OnFailure
      volumes:
      - name: ssh-key
        secret:
          secretName: {{ .Values.serverSetup.ssh.keySecretName }}
      - name: runner-scripts
        configMap:
          name: runner-scripts
