apiVersion: apps/v1
kind: Deployment
metadata:
  name: capi-management-cluster-setup
  labels:
    app: capi-management-cluster-setup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capi-management-cluster-setup
  template:
    metadata:
      labels:
        app: capi-management-cluster-setup
    spec:
      containers:
      - name: capi-management-cluster-setup
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ["/bin/sh", "-c"]
        args:
          - |
            if [ -f {{ .Values.setupCompletePath }} ]; then
              echo "Setup already completed, skipping..."
              exit 0
            fi

            apk add --no-cache jq curl
            latest_version=$(curl -s https://api.github.com/repos/kubernetes-sigs/cluster-api/releases/latest | jq -r '.tag_name')
            if [ -z "$latest_version" ]; then
              echo "Failed to fetch the latest version of clusterctl"
              exit 1
            fi

            curl -L "https://github.com/kubernetes-sigs/cluster-api/releases/download/${latest_version}/clusterctl-linux-amd64" -o /usr/local/bin/clusterctl
            if [ ! -f "/usr/local/bin/clusterctl" ]; then
              echo "Failed to download clusterctl"
              exit 1
            fi

            chmod +x /usr/local/bin/clusterctl
            CONTROL_PLANE_IP={{ .Values.controlPlaneIP }}
            sed -i "s/127.0.0.1/${CONTROL_PLANE_IP}/g" /etc/rancher/rke2/rke2.yaml

            export KUBECONFIG=/etc/rancher/rke2/rke2.yaml
            export CLUSTER_TOPOLOGY=true

            /usr/local/bin/clusterctl version
            /usr/local/bin/clusterctl init --infrastructure openstack

            touch {{ .Values.setupCompletePath }}
            exit 0
        volumeMounts:
        - name: kubeconfig
          mountPath: {{ .Values.kubeconfigPath }}
      volumes:
      - name: kubeconfig
        hostPath:
          path: {{ .Values.kubeconfigPath }}
          type: Directory
