apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-config
  namespace: default
data:
  install-clusterctl.sh: |
    #!/bin/bash
    set -e

    if command -v clusterctl &>/dev/null; then
      echo "clusterctl is already installed."
    else
      curl -L {{ .Values.serverSetup.clusterctlUrl }} -o /usr/local/bin/clusterctl
      chmod +x /usr/local/bin/clusterctl
    fi
    clusterctl version

  init-cluster.sh: |
    #!/bin/bash
    set -e

    if clusterctl version | grep "v1.6.2"; then
      echo "Management cluster is already initialized."
    else
      export KUBECONFIG={{ .Values.kubeconfig.path }}
      export CLUSTER_TOPOLOGY=true
      clusterctl init --infrastructure openstack
    fi
